name: Deploy to production

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Installing dependencies
              run: yarn install --frozen-lockfile

            - name: Populating secrets
              run: | 
                echo "${{ secrets.GCLOUD_SECRET }}" > /tmp/gcloud-secret.base64
                base64 --decode /tmp/gcloud-secret.base64 > gcloud-secret.json
                echo "GOOGLE_APPLICATION_CREDENTIALS=./gcloud-secret.json" > .env.local
                echo "SPREADSHEET_ID=${{ secrets.SHEET_ID_DEV }}" >> .env.local
                mkdir -p ~/.ssh
                echo "${{ secrets.DEPLOYBOT }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H ieee.iit.ac.lk >> ~/.ssh/known_hosts

            - name: Building
              run: yarn build

            - name: Deploy
              run: | 
                rsync -avz --delete .next/ deploybot@ieee.iit.ac.lk:/opt/codesprint-store/.next
                rsync -avz --delete public/ deploybot@ieee.iit.ac.lk:/opt/codesprint-store/public
                ssh deploybot@ieee.iit.ac.lk "cd /opt/codesprint-store && rm -f package.json gcloud-secret.json yarn.lock .env.local"
                scp package.json deploybot@ieee.iit.ac.lk:/opt/codesprint-store/package.json
                scp yarn.lock deploybot@ieee.iit.ac.lk:/opt/codesprint-store/yarn.lock
                scp .env.local deploybot@ieee.iit.ac.lk:/opt/codesprint-store/.env.local
                scp gcloud-secret.json deploybot@ieee.iit.ac.lk:/opt/codesprint-store/gcloud-secret.json
                ssh deploybot@ieee.iit.ac.lk "cd /opt/codesprint-store && yarn install --frozen-lockfile && pm2 restart codesprint-store"
